const companyTags = {
  AWS: [503,
  ['테라(Terra)',
   '매스프레소(Mathpresso)',
   '메디트(Medit)',
   '밸런스히어로 (트루밸런스)',
   '모비데이즈(Mobidays)',
   '마이리얼트립',
   '비브로스',
   'ab180',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '터치웍스(touchworks)',
   '아그레아블',
   '루닛(Lunit)',
   '닥터다이어리',
   '버즈아트(BBuzzArt)',
   '피움랩스(PIUM LABS)',
   '아틀라스가이드 (Atlas Guide)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '엔달고',
   'PUBG Corporation',
   '글로우데이즈(glowdayz)',
   '베스핀글로벌(Bespin)',
   '버즈빌(buzzvil)',
   '투어마케팅코리아',
   '트립비토즈(tripbtoz)',
   '스마트스터디(SMARTSTUDY)',
   '더파머스(마켓컬리)',
   '포잉(TRUST US)',
   '별별선생(티밸류와이즈)',
   '아키드로우',
   '마크로밀 (Macromill)',
   '푸른밤',
   '모인(MOIN)',
   '쏘카(SOCAR)',
   '비알오',
   '뷰티패스',
   '스터디 플러스 (Studyplus)',
   '스펙업애드',
   '비티씨씨코리아',
   '아만다(넥스트매치)',
   '큐피스트',
   '아크로고스 주식회사',
   '더루프',
   '위메프',
   '스타 팩토리 (Starfactory)',
   '(주)브레이브모바일(soomgo)',
   '변호사 닷컴',
   '젠가엑스피티이엘티디',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '플레이윙즈',
   '핀다 (Finda)',
   '한국신용데이터',
   '콘텐츠연합플랫폼(pooq)',
   'The Encore Company',
   '노티플러스',
   'Pulit',
   '인포뱅크',
   'Urbanfox Pte Ltd',
   '패션을부탁해',
   '백패커(idus)',
   '크리마 (크리마팩토리, 크리마랩)',
   'SUMMER',
   '엔젤스윙',
   '위드이노베이션',
   '플리토',
   '테라핀테크(테라펀딩)',
   '루나소프트',
   'R3',
   '비주얼(bejewel)',
   '버즈니(Buzzni)',
   '레이니스트(Banksalad)',
   '바닐라브릿지',
   '밸류앤드트러스트',
   'IDNSOFT',
   '한빗코',
   '옴니어스(Omnious)',
   'Gunosy',
   '에프앤에프(F&F)',
   '레진엔터테인먼트',
   '콜론디(Colondee)',
   '파레트코',
   '더커머스',
   '제로웹',
   '그렙(grepp)',
   '왁티(WAGTI)',
   '미스터픽',
   '마이리얼플랜(아이지넷)',
   '엑씽크',
   'Mobcast Games Inc.',
   '모두싸인',
   '텀블벅(Tumblbug)',
   'SK커뮤니케이션즈',
   'COLOPL(코로프라)',
   '넥슨재팬 (NEXON)',
   '디랩',
   '스테이지랩스',
   '메이트코퍼레이션(MEIT Corporation)',
   '스마트포스팅',
   '아이스크림에듀',
   'Talent Pool Project(Japan)',
   '마이뮤직테이스트',
   '리얼리티리플렉션',
   'RakSul, Inc.',
   '브래킷',
   '브랜디(Brandi)',
   '키드앱티브아시아',
   '노마드스타']],
  API: [461,
  ['원티드랩',
   '스윗트래커',
   '데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '체인파트너스',
   '야놀자(yanolja)',
   '버키(balky)',
   '마이리얼트립',
   'ab180',
   '콩테크(Kong-tech)',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '보이스로코',
   '딜라이트룸(Alarmy)',
   '버즈아트(BBuzzArt)',
   '피움랩스(PIUM LABS)',
   '아틀라스가이드 (Atlas Guide)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '글로우데이즈(glowdayz)',
   '베스핀글로벌(Bespin)',
   '티드(envicase)',
   '버즈빌(buzzvil)',
   '아이엠랩(I.M.LAB)',
   '투어마케팅코리아',
   '트립비토즈(tripbtoz)',
   '조이코퍼레이션(ZOYI)',
   '직토(Zikto)',
   '29CM(에이플러스비)',
   '비버이엔티',
   '포잉(TRUST US)',
   '튜터링',
   '아키드로우',
   '지닉스(zeniex)',
   '푸른밤',
   '모인(MOIN)',
   '오케이코인코리아',
   '뷰티패스',
   '台灣樂天市場',
   '인플루엔셜',
   '카카오페이지(podotree)',
   '엘리스',
   'Peer',
   '아만다(넥스트매치)',
   '큐피스트',
   '올림플래닛(ZipView)',
   '어반베이스(Urbanbase)',
   '루트에너지',
   '플레인베이글',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   'Jr코딩연구소',
   '(주)브레이브모바일(soomgo)',
   '오드컨셉',
   '노리(Knowre)',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '시원스쿨',
   '데일리(DAILY)',
   '플레이윙즈',
   '핀다 (Finda)',
   'The Encore Company',
   '레코벨(RECOBELL)',
   '클래스팅(Classting)',
   '휴레이포지티브',
   '인포뱅크',
   '펫닥',
   '이쿠얼키',
   '빙글(Vingle)',
   '퀄슨',
   '패션을부탁해',
   '백패커(idus)',
   '벤디스(식권대장)',
   '크리마 (크리마팩토리, 크리마랩)',
   'Crypton (벡터스주식회사)',
   '위드이노베이션',
   '다비오(Dabeeo)',
   '아이오앤코 코리아',
   '뉴오더',
   '테라핀테크(테라펀딩)',
   '아이엠폼',
   '버즈니(Buzzni)',
   '레이니스트(Banksalad)',
   '바닐라브릿지',
   '블록체인벤처스',
   'IDNSOFT',
   '옴니어스(Omnious)',
   '옐로스토리(Yellostory)',
   '시어스랩(Seerslab)',
   '레진엔터테인먼트',
   '콜론디(Colondee)',
   '파레트코',
   '더커머스',
   '야놀자트래블(야놀자펜션)',
   '왁티(WAGTI)',
   '미스터픽',
   '바로고(barogo)',
   '마이리얼플랜(아이지넷)',
   '머니투데이',
   '발란(BALAAN)',
   '레드벨벳벤처스',
   '마인즈랩',
   '마드라스체크',
   '엔비티(NBT, 캐시슬라이드)',
   '헬스커넥트',
   '워트인텔리전스',
   '뷰노',
   '화해(버드뷰)',
   '브래킷',
   '키드앱티브아시아',
   '노마드스타']],
  iOS: [333,
  ['알지피코리아(요기요,배달통)',
   'Talent Pool Project(Global)',
   '네이버랩스(NAVERLABS)',
   '쿠프마케팅',
   '딜라이트룸(Alarmy)',
   '피움랩스(PIUM LABS)',
   '티몬(Tmon)',
   '케어랩스(바비톡)',
   '티드(envicase)',
   '애니펜',
   '스퀘어랩',
   '토스랩(JANDI)',
   '스마트스터디(SMARTSTUDY)',
   '비버이엔티',
   '포지큐브',
   '프렌트립(프립)',
   'Blue Whale Foundation',
   '키즈노트',
   '스노우(SNOW)',
   'Level13',
   '스터디 플러스 (Studyplus)',
   '아주큐엠에스',
   '크로키닷컴(ZIGZAG/지그재그)',
   '비티씨씨코리아',
   '피알앤디컴퍼니(헤이딜러)',
   'XHIFT',
   '카닥',
   '크리에이트립',
   '핀다 (Finda)',
   '스타일쉐어',
   '힐세리온',
   '뤼이드(Riiid)',
   '오피지지(OP.GG)',
   '우아한형제들(배달의민족,Tech)',
   '로켓런치',
   '소리바다',
   'WeWork Korea',
   '차차크리에이션',
   '애드포스 인사이트(AD4th Insight)',
   '코인매니저',
   'CREARC',
   '레이니스트(Banksalad)',
   '바닐라브릿지',
   '케어랩스 굿닥',
   '시어스랩(Seerslab)',
   '파레트코',
   '마이쿤',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '싸이월드',
   '크몽(kmong)',
   'VCNC(비트윈)',
   '에버스핀',
   '알서포트(Rsupport)',
   'Penta Security Systems',
   '엔비티(NBT, 캐시슬라이드)',
   'Talent Pool Project(Japan)',
   'Talent Pool Project',
   '메디스태프',
   '데브시스터즈(Devsisters)',
   'KLab Inc.',
   '화해(버드뷰)',
   'JX 통신사',
   '키드앱티브아시아']],
  C: [333,
  ['매스프레소(Mathpresso)',
   '메디트(Medit)',
   '야놀자(yanolja)',
   '(주)쿠차',
   '넥슨코리아(NEXON)',
   'Talent Pool Project(Global)',
   '루닛(Lunit)',
   '딜라이트룸(Alarmy)',
   'SendBird(센드버드)',
   '메쉬코리아(MeshKorea)',
   '수아랩',
   'PUBG Corporation',
   '티드(envicase)',
   '데일리금융그룹',
   '애니펜',
   '토스랩(JANDI)',
   '스마트스터디(SMARTSTUDY)',
   '포잉(TRUST US)',
   '포지큐브',
   '유라이크코리아',
   'Blue Whale Foundation',
   '사이버다임',
   '스노우(SNOW)',
   'Tencent',
   '아주큐엠에스',
   '더루프',
   '비피소프트',
   'dooub(둡)',
   '미로쿠 정보 서비스',
   '오드컨셉',
   '카닥',
   '넷마블엔투',
   '더블미코리아',
   '인포뱅크',
   '힐세리온',
   'Bepro',
   '뤼이드(Riiid)',
   'Crypton (벡터스주식회사)',
   '웨이브일렉트로닉스',
   '우아한형제들(배달의민족,Tech)',
   '스캐터랩(Scatterlab)',
   '로켓런치',
   '뉴오더',
   '테라핀테크(테라펀딩)',
   '차차크리에이션',
   '넥스트리밍',
   'CREARC',
   '케어랩스 굿닥',
   '블록체인벤처스',
   '어웨어(AWAIR)',
   '맵퍼스',
   '브릴리언츠 (Brilliantts)',
   '마이쿤',
   '더커머스',
   '야놀자트래블(야놀자펜션)',
   '싸이월드',
   '바로고(barogo)',
   '마이리얼플랜(아이지넷)',
   '여행박사',
   '360Channel',
   'VCNC(비트윈)',
   '닛산 (NISSAN)',
   '마인즈랩',
   '에버스핀',
   '알서포트(Rsupport)',
   '바이시큐(Bisecu)',
   '코인토스',
   'Penta Security Systems',
   '엔비티(NBT, 캐시슬라이드)',
   '밀리만코리아(Milliman)',
   'Talent Pool Project(Japan)',
   'Talent Pool Project',
   '두나무(카카오스탁/업비트)',
   '오비고(Obigo)',
   '뷰노',
   '데브시스터즈(Devsisters)',
   '브랜디(Brandi)',
   '시큐아이',
   '헤카스(HECAS)',
   '엑스브레인(XBRAIN)']],
  Python: [305,
  ['매스프레소(Mathpresso)',
   '카카오모빌리티(KakaoMobility)',
   'SK텔레콤(SKT)',
   '넥슨코리아(NEXON)',
   'ab180',
   '코인원(coinone)',
   'Carousell',
   '뉴스젤리(Newsjelly)',
   '루닛(Lunit)',
   '피움랩스(PIUM LABS)',
   'NAVER Corp(네이버)',
   'PUBG Corporation',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '스마트스터디(SMARTSTUDY)',
   '유라이크코리아',
   '푸른밤',
   '사이버다임',
   '쏘카(SOCAR)',
   '台灣樂天市場',
   '인플루엔셜',
   '카카오페이지(podotree)',
   '엘리스',
   '다노(DANO)',
   '아주큐엠에스',
   '스펙업애드',
   '아만다(넥스트매치)',
   '큐피스트',
   '더루프',
   '힐링페이퍼',
   '변호사 닷컴',
   '오드컨셉',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '디셈버앤컴퍼니',
   '드라마앤컴퍼니(리멤버)',
   '핀다 (Finda)',
   '한국신용데이터',
   '스타일쉐어',
   '에잇퍼센트(8PERCENT)',
   'Bepro',
   '백패커(idus)',
   '크리마 (크리마팩토리, 크리마랩)',
   '스캐터랩(Scatterlab)',
   '룩인바디',
   'R3',
   '리디 주식회사(RIDIBOOKS)',
   '센트비(Sentbe)',
   '버즈니(Buzzni)',
   '레이니스트(Banksalad)',
   '이큐포올',
   '파레트코',
   '트리플',
   '더커머스',
   '제로웹',
   'SK커뮤니케이션즈',
   'COLOPL(코로프라)',
   '디랩',
   '마인즈랩',
   '렌딧(LENDIT)',
   '아이스크림에듀',
   'Talent Pool Project(Japan)',
   '두나무(카카오스탁/업비트)',
   '브이픽스메디칼',
   '뷰노',
   '브랜디(Brandi)',
   'GS SHOP',
   '엑스브레인(XBRAIN)']],
  Java: [264,
  ['스윗트래커',
   '메디트(Medit)',
   '모비데이즈(Mobidays)',
   'Talent Pool Project(Global)',
   '아그레아블',
   '보이스로코',
   '버즈아트(BBuzzArt)',
   'NAVER Corp(네이버)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '글로우데이즈(glowdayz)',
   '티드(envicase)',
   '버즈빌(buzzvil)',
   '애니펜',
   '스퀘어랩',
   '코인플러그(Coinplug)',
   '유라이크코리아',
   '마크로밀 (Macromill)',
   '지닉스(zeniex)',
   '푸른밤',
   '台灣樂天市場',
   '카카오페이지(podotree)',
   '에스알유니버스',
   '크로키닷컴(ZIGZAG/지그재그)',
   '아만다(넥스트매치)',
   'Obelab',
   '더루프',
   '플레인베이글',
   '수퍼브(superb)',
   '오드컨셉',
   '카닥',
   '스페컴',
   '레코벨(RECOBELL)',
   '비즈톡',
   '노티플러스',
   'Pulit',
   '인포뱅크',
   '와디즈',
   '오피지지(OP.GG)',
   '스캐터랩(Scatterlab)',
   '아이오앤코 코리아',
   '테라핀테크(테라펀딩)',
   '멜리펀트',
   'R3',
   '리디 주식회사(RIDIBOOKS)',
   '디케이테크인(dk techin) a kakao company',
   '라쿠텐(Rakuten)',
   '에프앤에프(F&F)',
   '맵퍼스',
   '콜론디(Colondee)',
   '트리플',
   '더커머스',
   '요쿠스(Jocoos)',
   '360Channel',
   '레드벨벳벤처스',
   'SK커뮤니케이션즈',
   '아르고넷',
   '스마트포스팅',
   '마인즈랩',
   '렌딧(LENDIT)',
   '마드라스체크',
   '아이스크림에듀',
   'VSN',
   'Talent Pool Project(Japan)',
   '두나무(카카오스탁/업비트)',
   '니프티',
   '워트인텔리전스',
   '뷰노',
   '스프링웍스(Springworks)',
   'GS SHOP',
   '키드앱티브아시아',
   '엑스브레인(XBRAIN)']],
  Android: [263,
  ['스윗트래커',
   'Talent Pool Project(Global)',
   '네이버랩스(NAVERLABS)',
   '쿠프마케팅',
   '피움랩스(PIUM LABS)',
   '프리윌린',
   '티드(envicase)',
   '버즈빌(buzzvil)',
   '아이엠랩(I.M.LAB)',
   '애니펜',
   '스퀘어랩',
   '스마트스터디(SMARTSTUDY)',
   '29CM(에이플러스비)',
   '포지큐브',
   '스노우(SNOW)',
   '스터디 플러스 (Studyplus)',
   '에스알유니버스',
   '아주큐엠에스',
   '(주)비비비',
   '플레인베이글',
   'XHIFT',
   '카닥',
   '크리에이트립',
   '핀다 (Finda)',
   '스타일쉐어',
   '아라드네트웍스(ARAD)',
   '힐세리온',
   '뉴오더',
   'WeWork Korea',
   '멜리펀트',
   '레이니스트(Banksalad)',
   '바닐라브릿지',
   '시어스랩(Seerslab)',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '크몽(kmong)',
   '360Channel',
   '스마트포스팅',
   '에버스핀',
   '엔비티(NBT, 캐시슬라이드)',
   'Talent Pool Project(Japan)',
   '데브시스터즈(Devsisters)',
   'KLab Inc.',
   '헤카스(HECAS)',
   'JX 통신사',
   '키드앱티브아시아']],
  Web: [257,
  ['데이블(Dable)',
   '메디트(Medit)',
   '야놀자(yanolja)',
   '스튜디오씨드코리아',
   'ab180',
   '쿠프마케팅',
   '루닛(Lunit)',
   'KT NexR',
   '티드(envicase)',
   '스타벅스 커피 재팬 (Starbucks Coffee Japan)',
   '29CM(에이플러스비)',
   '소다크루',
   '더파머스(마켓컬리)',
   '비알오',
   'Peer',
   '스펙업애드',
   '큐피스트',
   '어반베이스(Urbanbase)',
   '스타 팩토리 (Starfactory)',
   '변호사 닷컴',
   'dooub(둡)',
   '카닥',
   '클래스팅(Classting)',
   '이쿠얼키',
   '패션을부탁해',
   '백패커(idus)',
   '크리마 (크리마팩토리, 크리마랩)',
   'Crypton (벡터스주식회사)',
   '다비오(Dabeeo)',
   '뉴오더',
   'Donuts',
   '센트비(Sentbe)',
   '블록체인벤처스',
   '아모레퍼시픽(AMOREPACIFIC)',
   '디케이테크인(dk techin) a kakao company',
   'Gunosy',
   '파레트코',
   '마이쿤',
   '야놀자트래블(야놀자펜션)',
   '미스터픽',
   'GameWith',
   '360Channel',
   '메탑스 (metaps)',
   '스테이지랩스',
   '엔비티(NBT, 캐시슬라이드)',
   'Talent Pool Project(Japan)',
   '두나무(카카오스탁/업비트)',
   '브래킷',
   '씨엔알리서치',
   'JX 통신사']],
  React: [239,
  ['원티드랩',
   '데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '메디트(Medit)',
   '솔라커넥트',
   '버키(balky)',
   '스튜디오씨드코리아',
   '더블유컨셉코리아(wconcept)',
   '올스타메니지먼트',
   '아틀라스가이드 (Atlas Guide)',
   '조이코퍼레이션(ZOYI)',
   '소다크루',
   '콜라비팀(Collabee)',
   '포지큐브',
   '유라이크코리아',
   'Blue Whale Foundation',
   '지닉스(zeniex)',
   'Shopee',
   '푸른밤',
   'Level13',
   '오케이코인코리아',
   '뷰티패스',
   '인플루엔셜',
   'Peer',
   '아주큐엠에스',
   '스펙업애드',
   '어반베이스(Urbanbase)',
   '루트에너지',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '수퍼브(superb)',
   '힐링페이퍼',
   'Jr코딩연구소',
   '(주)브레이브모바일(soomgo)',
   '카닥',
   '데일리(DAILY)',
   'Allganize Korea',
   '지니웍스(Genieworks, Inc.)',
   '플레이윙즈',
   '핀다 (Finda)',
   '펫닥',
   '이쿠얼키',
   '뤼이드(Riiid)',
   '컬쳐히어로',
   'Donuts',
   '애드포스 인사이트(AD4th Insight)',
   '멜리펀트',
   'CREARC',
   '아이엠폼',
   '레이니스트(Banksalad)',
   '밸류앤드트러스트',
   '레저큐',
   '한빗코',
   '파레트코',
   '모두싸인',
   '스테이지랩스',
   '메디블록(MediBloc)',
   '아이스크림에듀',
   '이디엄',
   '뷰노',
   '(주)트릴리어네어',
   '노마드스타']],
  Linux: [200,
  ['데이블(Dable)',
   '(주)쿠차',
   '코인원(coinone)',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '닥터다이어리',
   '데일리금융그룹',
   '투어마케팅코리아',
   '더파머스(마켓컬리)',
   '포잉(TRUST US)',
   '포지큐브',
   '튜터링',
   '마크로밀 (Macromill)',
   'Shopee Singapore Private Limited',
   '뷰티패스',
   '台灣樂天市場',
   '렛유인',
   '큐피스트',
   '위메프',
   '오파테크',
   '오드컨셉',
   '트루쇼트코리아(TrueShortKorea)',
   '시원스쿨',
   '스페컴',
   '콘텐츠연합플랫폼(pooq)',
   '레코벨(RECOBELL)',
   'Urbanfox Pte Ltd',
   'Electronic Arts Korea I SPEARHEAD',
   '와디즈',
   '블로코(blocko)',
   '에잇퍼센트(8PERCENT)',
   '크리마 (크리마팩토리, 크리마랩)',
   '웨이브일렉트로닉스',
   '다비오(Dabeeo)',
   '소리바다',
   '테라핀테크(테라펀딩)',
   'R3',
   '밸류앤드트러스트',
   '라쿠텐(Rakuten)',
   '어웨어(AWAIR)',
   '파레트코',
   '미스터픽',
   'Chengbao',
   '원스토어',
   '발란(BALAAN)',
   '360Channel',
   'Mobcast Games Inc.',
   'SK커뮤니케이션즈',
   'COLOPL(코로프라)',
   '넥슨재팬 (NEXON)',
   '스마트포스팅',
   '마인즈랩',
   '코인토스',
   '마이뮤직테이스트',
   '브이픽스메디칼',
   '오비고(Obigo)',
   '워트인텔리전스',
   '씨엔알리서치',
   '투게더앱스',
   '(주)집꾸미기',
   '원더피플']],
  UI: [190,
  ['데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '솔라커넥트',
   '네이버랩스(NAVERLABS)',
   '올스타메니지먼트',
   '딜라이트룸(Alarmy)',
   'KT NexR',
   '프리윌린',
   '메쉬코리아(MeshKorea)',
   '티드(envicase)',
   '버즈빌(buzzvil)',
   '아이엠랩(I.M.LAB)',
   '애니펜',
   '비버이엔티',
   '코인플러그(Coinplug)',
   '포지큐브',
   '튜터링',
   '지닉스(zeniex)',
   'Shopee',
   '스노우(SNOW)',
   '에스알유니버스',
   '아주큐엠에스',
   '피알앤디컴퍼니(헤이딜러)',
   '루트에너지',
   '티포트(tport)',
   '(주)브레이브모바일(soomgo)',
   '데일리(DAILY)',
   'Allganize Korea',
   '패션을부탁해',
   '벤디스(식권대장)',
   'Crypton (벡터스주식회사)',
   '오피지지(OP.GG)',
   '키클롭스',
   '우아한형제들(배달의민족,Tech)',
   '뉴오더',
   'Donuts',
   '바람인터내셔날(DEAR DAHLIA)',
   '리디 주식회사(RIDIBOOKS)',
   '밸류앤드트러스트',
   '레저큐',
   '한빗코',
   '번개장터(셀잇)',
   '시어스랩(Seerslab)',
   '싸이월드',
   '360Channel',
   '플랫팜',
   '엔비티(NBT, 캐시슬라이드)',
   '메디스태프',
   '미탭스플러스']],
  MySQL: [182,
  ['테라(Terra)',
   '데이블(Dable)',
   '카카오모빌리티(KakaoMobility)',
   '(주)쿠차',
   '이디엠에듀케이션',
   '코인원(coinone)',
   '콩테크(Kong-tech)',
   '터치웍스(touchworks)',
   '루닛(Lunit)',
   '버즈아트(BBuzzArt)',
   '글로우데이즈(glowdayz)',
   '베스핀글로벌(Bespin)',
   '버즈빌(buzzvil)',
   '스퀘어랩',
   '아키드로우',
   'Shopee Singapore Private Limited',
   '쏘카(SOCAR)',
   '비알오',
   '台灣樂天市場',
   '카카오페이지(podotree)',
   '스터디 플러스 (Studyplus)',
   '다노(DANO)',
   '루트에너지',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '스타 팩토리 (Starfactory)',
   '변호사 닷컴',
   '시원스쿨',
   '스페컴',
   '콘텐츠연합플랫폼(pooq)',
   'Pulit',
   '인포뱅크',
   'Urbanfox Pte Ltd',
   '와디즈',
   '퀄슨',
   '블로코(blocko)',
   '벤디스(식권대장)',
   '엔젤스윙',
   '테라핀테크(테라펀딩)',
   '디케이테크인(dk techin) a kakao company',
   '라쿠텐(Rakuten)',
   '제로웹',
   '마이리얼플랜(아이지넷)',
   '360Channel',
   '텀블벅(Tumblbug)',
   'COLOPL(코로프라)',
   '스마트포스팅',
   '아이스크림에듀',
   'Talent Pool Project(Japan)',
   '니프티',
   'RakSul, Inc.',
   '투게더앱스',
   '키드앱티브아시아']],
  DB: [175,
  ['데이블(Dable)',
   '모비데이즈(Mobidays)',
   '버키(balky)',
   '(주)쿠차',
   '뉴스젤리(Newsjelly)',
   '닥터다이어리',
   '올스타메니지먼트',
   '스마트스터디(SMARTSTUDY)',
   '별별선생(티밸류와이즈)',
   '튜터링',
   '아키드로우',
   '유라이크코리아',
   '마크로밀 (Macromill)',
   'Shopee Singapore Private Limited',
   '모인(MOIN)',
   '쏘카(SOCAR)',
   '台灣樂天市場',
   '피알앤디컴퍼니(헤이딜러)',
   '루트에너지',
   '시원스쿨',
   '지니웍스(Genieworks, Inc.)',
   '호텔나우(봉봉랩)',
   '핀다 (Finda)',
   '콘텐츠연합플랫폼(pooq)',
   '넷마블엔투',
   '인포뱅크',
   'Electronic Arts Korea I SPEARHEAD',
   '백패커(idus)',
   '크리마 (크리마팩토리, 크리마랩)',
   '위드이노베이션',
   '다비오(Dabeeo)',
   '뉴오더',
   '소리바다',
   '밀리의서재',
   '루나소프트',
   '비주얼(bejewel)',
   '아이엠폼',
   '밸류앤드트러스트',
   'IDNSOFT',
   '랭킹볼코리아',
   '마이쿤',
   '360Channel',
   '엑씽크',
   'SK커뮤니케이션즈',
   '메이트코퍼레이션(MEIT Corporation)',
   '스마트포스팅',
   '마드라스체크',
   '브이픽스메디칼',
   'RakSul, Inc.',
   '원더피플',
   '핀톡(Fintalk)',
   '노마드스타']],
  CSS: [169,
  ['데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '체인파트너스',
   '야놀자(yanolja)',
   '솔라커넥트',
   '버키(balky)',
   '스튜디오씨드코리아',
   '뉴스젤리(Newsjelly)',
   '올스타메니지먼트',
   'KT NexR',
   '아틀라스가이드 (Atlas Guide)',
   '베스핀글로벌(Bespin)',
   '조이코퍼레이션(ZOYI)',
   '포지큐브',
   '유라이크코리아',
   '지닉스(zeniex)',
   '오케이코인코리아',
   'Peer',
   '스펙업애드',
   '렛유인',
   '아크로고스 주식회사',
   '올림플래닛(ZipView)',
   '어반베이스(Urbanbase)',
   '루트에너지',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   'XHIFT',
   '(주)브레이브모바일(soomgo)',
   '변호사 닷컴',
   '오드컨셉',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '디셈버앤컴퍼니',
   '데일리(DAILY)',
   'Allganize Korea',
   '지니웍스(Genieworks, Inc.)',
   '핀다 (Finda)',
   '펫닥',
   '이쿠얼키',
   '크리마 (크리마팩토리, 크리마랩)',
   '컬쳐히어로',
   '다비오(Dabeeo)',
   'Donuts',
   'R3',
   '아이엠폼',
   '밸류앤드트러스트',
   '라쿠텐(Rakuten)',
   '야놀자트래블(야놀자펜션)',
   '머니투데이',
   '스테이지랩스',
   '스마트포스팅',
   '이디엄',
   'RakSul, Inc.',
   '미탭스플러스',
   '투게더앱스']],
  HTML: [168,
  ['데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '체인파트너스',
   '솔라커넥트',
   '스튜디오씨드코리아',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '올스타메니지먼트',
   'KT NexR',
   '아틀라스가이드 (Atlas Guide)',
   '베스핀글로벌(Bespin)',
   '조이코퍼레이션(ZOYI)',
   '포지큐브',
   '유라이크코리아',
   '지닉스(zeniex)',
   '오케이코인코리아',
   'Peer',
   '스펙업애드',
   '렛유인',
   '아크로고스 주식회사',
   '올림플래닛(ZipView)',
   '어반베이스(Urbanbase)',
   '루트에너지',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '수퍼브(superb)',
   '티포트(tport)',
   '힐링페이퍼',
   'XHIFT',
   '(주)브레이브모바일(soomgo)',
   '뉴지스탁(DFG)',
   '변호사 닷컴',
   '오드컨셉',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '디셈버앤컴퍼니',
   '데일리(DAILY)',
   'Allganize Korea',
   '지니웍스(Genieworks, Inc.)',
   '핀다 (Finda)',
   '펫닥',
   '이쿠얼키',
   '와디즈',
   '크리마 (크리마팩토리, 크리마랩)',
   '컬쳐히어로',
   '다비오(Dabeeo)',
   'Donuts',
   'R3',
   '아이엠폼',
   '밸류앤드트러스트',
   '라쿠텐(Rakuten)',
   '머니투데이',
   '메탑스 (metaps)',
   '스테이지랩스',
   '스마트포스팅',
   '오비고(Obigo)',
   '이디엄',
   'RakSul, Inc.',
   '뷰노',
   '미탭스플러스',
   '투게더앱스']],
  Git: [156,
  ['테라(Terra)',
   '데이블(Dable)',
   '비바리퍼블리카(Toss)',
   '버키(balky)',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '닥터다이어리',
   '올스타메니지먼트',
   '딜라이트룸(Alarmy)',
   '버즈아트(BBuzzArt)',
   '프리윌린',
   '엔달고',
   '글로우데이즈(glowdayz)',
   '케어랩스(바비톡)',
   '티드(envicase)',
   '토스랩(JANDI)',
   '비버이엔티',
   '포지큐브',
   '키즈노트',
   '모인(MOIN)',
   '비알오',
   '엘리스',
   '에스알유니버스',
   '다노(DANO)',
   '스펙업애드',
   '더루프',
   '비피소프트',
   'XHIFT',
   '변호사 닷컴',
   '오드컨셉',
   '카닥',
   '데일리(DAILY)',
   '플레이윙즈',
   '핀다 (Finda)',
   '휴레이포지티브',
   '스타일쉐어',
   '인포뱅크',
   '펫닥',
   '이쿠얼키',
   'Urbanfox Pte Ltd',
   '와디즈',
   '블로코(blocko)',
   '패션을부탁해',
   '벤디스(식권대장)',
   '컬쳐히어로',
   '로켓런치',
   '애드포스 인사이트(AD4th Insight)',
   '케어랩스 굿닥',
   '옐로스토리(Yellostory)',
   '파레트코',
   '더커머스',
   '제로웹',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '왁티(WAGTI)',
   '크몽(kmong)',
   '레드벨벳벤처스',
   '모두싸인',
   '디랩',
   '스테이지랩스',
   '메이트코퍼레이션(MEIT Corporation)',
   'RakSul, Inc.',
   '브랜디(Brandi)',
   '미탭스플러스',
   '헤카스(HECAS)',
   '엑스브레인(XBRAIN)',
   '노마드스타']],
  SQL: [156,
  ['메디트(Medit)',
   '밸런스히어로 (트루밸런스)',
   '카카오모빌리티(KakaoMobility)',
   'SK텔레콤(SKT)',
   'ab180',
   '코인원(coinone)',
   'Carousell',
   '더블유컨셉코리아(wconcept)',
   '티드(envicase)',
   '버즈빌(buzzvil)',
   '투어마케팅코리아',
   'Blue Whale Foundation',
   'Shopee Singapore Private Limited',
   '台灣樂天市場',
   '렛유인',
   'XHIFT',
   '뉴지스탁(DFG)',
   '드라마앤컴퍼니(리멤버)',
   'Electronic Arts Korea I SPEARHEAD',
   '크리마 (크리마팩토리, 크리마랩)',
   '비주얼(bejewel)',
   '센트비(Sentbe)',
   '아이엠폼',
   '아모레퍼시픽(AMOREPACIFIC)',
   'Gunosy',
   '제로웹',
   '마이리얼플랜(아이지넷)',
   '머니투데이',
   '여행박사',
   'Mobcast Games Inc.',
   'SK커뮤니케이션즈',
   '넥슨재팬 (NEXON)',
   '렌딧(LENDIT)',
   '아이스크림에듀',
   '마이뮤직테이스트',
   '코코네(cocone)',
   '원더피플']],
  MS: [142,
  ['메디트(Medit)',
   '뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '루닛(Lunit)',
   '베스핀글로벌(Bespin)',
   '스타벅스 커피 재팬 (Starbucks Coffee Japan)',
   '마크로밀 (Macromill)',
   '스터디 플러스 (Studyplus)',
   '스타 팩토리 (Starfactory)',
   '뉴지스탁(DFG)',
   '변호사 닷컴',
   '미로쿠 정보 서비스',
   'SoftBank (소프트뱅크)',
   'Donuts',
   'CREARC',
   'WeWork Japan',
   '라쿠텐(Rakuten)',
   'Gunosy',
   '브릴리언츠 (Brilliantts)',
   'PERSOL TECHNOLOGY STAFF (퍼솔 테크놀로지 스태프)',
   'GameWith',
   '여행박사',
   '360Channel',
   'LIFE DESIGN COMPANY',
   '닛산 (NISSAN)',
   '메탑스 (metaps)',
   'Mobcast Games Inc.',
   'COLOPL(코로프라)',
   '넥슨재팬 (NEXON)',
   '밀리만코리아(Milliman)',
   'VSN',
   'Talent Pool Project(Japan)',
   '니프티',
   'RakSul, Inc.',
   '뷰노',
   '브래킷',
   '코코네(cocone)',
   '원더피플',
   'JX 통신사',
   '마이크로 애드']],
  PHP: [140,
  ['체인파트너스',
   '야놀자(yanolja)',
   '이디엠에듀케이션',
   '엠비아이솔루션',
   '글로우데이즈(glowdayz)',
   '베스핀글로벌(Bespin)',
   '투어마케팅코리아',
   '더파머스(마켓컬리)',
   '포잉(TRUST US)',
   '별별선생(티밸류와이즈)',
   '유라이크코리아',
   '큐피스트',
   '아크로고스 주식회사',
   'Jr코딩연구소',
   '변호사 닷컴',
   '카닥',
   '시원스쿨',
   '노티플러스',
   '블로코(blocko)',
   '백패커(idus)',
   'Crypton (벡터스주식회사)',
   '위드이노베이션',
   '다비오(Dabeeo)',
   '루나소프트',
   '아이엠폼',
   '에프앤에프(F&F)',
   '델레오(Deleo)',
   '더커머스',
   '야놀자트래블(야놀자펜션)',
   '미스터픽',
   '머니투데이',
   '발란(BALAAN)',
   '360Channel',
   '레드벨벳벤처스',
   'SK커뮤니케이션즈',
   '스마트포스팅',
   'Talent Pool Project(Japan)',
   '니프티',
   'RakSul, Inc.',
   '브랜디(Brandi)',
   '투게더앱스',
   '원더피플',
   '해커스어학원']],
  Node: [125,
  ['테라(Terra)',
   '데이블(Dable)',
   '엠비아이솔루션',
   '아그레아블',
   '닥터다이어리',
   '버즈아트(BBuzzArt)',
   '피움랩스(PIUM LABS)',
   '티드(envicase)',
   '트립비토즈(tripbtoz)',
   '튜터링',
   '아키드로우',
   'Blue Whale Foundation',
   '모인(MOIN)',
   '오케이코인코리아',
   '뷰티패스',
   '아주큐엠에스',
   '루트에너지',
   '힐링페이퍼',
   '스타 팩토리 (Starfactory)',
   'Allganize Korea',
   '핀다 (Finda)',
   'The Encore Company',
   '플리토',
   '밸류앤드트러스트',
   'IDNSOFT',
   '에프앤에프(F&F)',
   '왁티(WAGTI)',
   '360Channel',
   '레드벨벳벤처스',
   '스테이지랩스',
   '메디블록(MediBloc)',
   '마드라스체크',
   '뷰노',
   '노마드스타']],
  R: [108,
  ['메디트(Medit)',
   '모비데이즈(Mobidays)',
   '카카오모빌리티(KakaoMobility)',
   'SK텔레콤(SKT)',
   '버키(balky)',
   '넥슨코리아(NEXON)',
   'SendBird(센드버드)',
   '유저해빗(UserHabit)',
   '수아랩',
   '아키드로우',
   '유라이크코리아',
   '(주)브레이브모바일(soomgo)',
   'dooub(둡)',
   '핀다 (Finda)',
   '더블미코리아',
   '크리마 (크리마팩토리, 크리마랩)',
   '룩인바디',
   '퍼플랩스 PurpleLabs',
   'R3',
   '센트비(Sentbe)',
   '아모레퍼시픽(AMOREPACIFIC)',
   '한빗코',
   '어웨어(AWAIR)',
   '알서포트(Rsupport)',
   '코인토스',
   '아이스크림에듀',
   '밀리만코리아(Milliman)',
   '리얼리티리플렉션',
   '코코네(cocone)',
   '브랜디(Brandi)']],
  Ruby: [105,
  ['사이버다임',
   '스터디 플러스 (Studyplus)',
   '아만다(넥스트매치)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '변호사 닷컴',
   '카닥',
   '클래스팅(Classting)',
   '패션을부탁해',
   '크리마 (크리마팩토리, 크리마랩)',
   '바닐라브릿지',
   '랭킹볼코리아',
   'Gunosy',
   '더커머스',
   '텀블벅(Tumblbug)',
   'COLOPL(코로프라)',
   'Talent Pool Project(Japan)',
   '니프티',
   'RakSul, Inc.',
   '뷰노',
   '브래킷']],
  RESTful: [104,
  ['비바리퍼블리카(Toss)',
   '버키(balky)',
   '딜라이트룸(Alarmy)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '글로우데이즈(glowdayz)',
   '토스랩(JANDI)',
   '29CM(에이플러스비)',
   '비버이엔티',
   '튜터링',
   '아키드로우',
   '모인(MOIN)',
   '뷰티패스',
   '台灣樂天市場',
   '인플루엔셜',
   '올림플래닛(ZipView)',
   '어반베이스(Urbanbase)',
   '플레인베이글',
   '카닥',
   '이쿠얼키',
   '뉴오더',
   '아이엠폼',
   '콜론디(Colondee)',
   '야놀자트래블(야놀자펜션)',
   '왁티(WAGTI)',
   '발란(BALAAN)',
   '마드라스체크',
   '워트인텔리전스',
   '뷰노']],
  Vue: [103,
  ['비바리퍼블리카(Toss)',
   '솔라커넥트',
   '버키(balky)',
   '더블유컨셉코리아(wconcept)',
   '버즈아트(BBuzzArt)',
   '아틀라스가이드 (Atlas Guide)',
   '엔달고',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '포잉(TRUST US)',
   '포지큐브',
   '지닉스(zeniex)',
   '비알오',
   'Peer',
   '올림플래닛(ZipView)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '수퍼브(superb)',
   '힐링페이퍼',
   '변호사 닷컴',
   '카닥',
   '데일리(DAILY)',
   '플레이윙즈',
   '핀다 (Finda)',
   '이쿠얼키',
   'Donuts',
   '테라핀테크(테라펀딩)',
   '애드포스 인사이트(AD4th Insight)',
   '아이엠폼',
   '모두싸인',
   '아이스크림에듀',
   'RakSul, Inc.',
   '노마드스타']],
  UX: [98,
  ['비바리퍼블리카(Toss)',
   'SK텔레콤(SKT)',
   '네이버랩스(NAVERLABS)',
   '올스타메니지먼트',
   '딜라이트룸(Alarmy)',
   '프리윌린',
   '스퀘어랩',
   '지닉스(zeniex)',
   '피알앤디컴퍼니(헤이딜러)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '티포트(tport)',
   'Allganize Korea',
   '패션을부탁해',
   '벤디스(식권대장)',
   'Donuts',
   '바람인터내셔날(DEAR DAHLIA)',
   '넥스트리밍',
   '코인매니저',
   '번개장터(셀잇)',
   '크몽(kmong)',
   '360Channel',
   '알서포트(Rsupport)',
   '플랫팜',
   '메디스태프',
   '미탭스플러스']],
  Swift: [96,
  ['알지피코리아(요기요,배달통)',
   'Talent Pool Project(Global)',
   '딜라이트룸(Alarmy)',
   '스퀘어랩',
   '비버이엔티',
   '키즈노트',
   '스터디 플러스 (Studyplus)',
   '비티씨씨코리아',
   '피알앤디컴퍼니(헤이딜러)',
   '비피소프트',
   '오드컨셉',
   '카닥',
   '뤼이드(Riiid)',
   '우아한형제들(배달의민족,Tech)',
   '로켓런치',
   '뉴오더',
   '코인매니저',
   'CREARC',
   '레이니스트(Banksalad)',
   '케어랩스 굿닥',
   '마이쿤',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '싸이월드',
   '바로고(barogo)',
   '크몽(kmong)',
   '360Channel',
   'VCNC(비트윈)',
   'Penta Security Systems',
   '엔비티(NBT, 캐시슬라이드)',
   'Talent Pool Project']],
  Data: [93,
  ['밸런스히어로 (트루밸런스)',
   'SK텔레콤(SKT)',
   '넥슨코리아(NEXON)',
   'ab180',
   'Carousell',
   '루닛(Lunit)',
   '토스랩(JANDI)',
   '台灣樂天市場',
   '다노(DANO)',
   '트루쇼트코리아(TrueShortKorea)',
   'Allganize Korea',
   '지니웍스(Genieworks, Inc.)',
   '핀다 (Finda)',
   '룩인바디',
   'R3',
   '마이쿤',
   '렌딧(LENDIT)',
   '밀리만코리아(Milliman)',
   '키드앱티브아시아',
   '엑스브레인(XBRAIN)']],
  Framework: [88,
  ['SK텔레콤(SKT)',
   '뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '보이스로코',
   '글로우데이즈(glowdayz)',
   '티드(envicase)',
   '아이엠랩(I.M.LAB)',
   '아키드로우',
   '유라이크코리아',
   '지닉스(zeniex)',
   '푸른밤',
   '비알오',
   '큐피스트',
   '수퍼브(superb)',
   'Jr코딩연구소',
   'Pulit',
   '백패커(idus)',
   '다비오(Dabeeo)',
   'VCNC(비트윈)',
   '오비고(Obigo)',
   '스프링웍스(Springworks)',
   '헤카스(HECAS)',
   '투게더앱스',
   '(주)집꾸미기',
   '엑스브레인(XBRAIN)']],
  Docker: [87,
  ['루닛(Lunit)',
   '버즈빌(buzzvil)',
   '아키드로우',
   '푸른밤',
   '뷰티패스',
   '다노(DANO)',
   '젠가엑스피티이엘티디',
   '트루쇼트코리아(TrueShortKorea)',
   'Allganize Korea',
   '이쿠얼키',
   'Urbanfox Pte Ltd',
   'Electronic Arts Korea I SPEARHEAD',
   '플리토',
   'R3',
   '레이니스트(Banksalad)',
   '옴니어스(Omnious)',
   '라쿠텐(Rakuten)',
   '그렙(grepp)',
   '메탑스 (metaps)',
   '텀블벅(Tumblbug)',
   '마이뮤직테이스트']],
  Redis: [86,
  ['데이블(Dable)',
   '비브로스',
   '엠비아이솔루션',
   '뉴스젤리(Newsjelly)',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '포잉(TRUST US)',
   '푸른밤',
   '카카오페이지(podotree)',
   '엘리스',
   '스터디 플러스 (Studyplus)',
   '다노(DANO)',
   '큐피스트',
   '피알앤디컴퍼니(헤이딜러)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '스타 팩토리 (Starfactory)',
   'Allganize Korea',
   '인포뱅크',
   'Electronic Arts Korea I SPEARHEAD',
   '크리마 (크리마팩토리, 크리마랩)',
   '플리토',
   '소리바다',
   '라쿠텐(Rakuten)',
   '파레트코',
   '발란(BALAAN)',
   '360Channel']],
  QA: [86, ['카닥', '와디즈', 'GameWith', '마인즈랩']],
  development: [85,
  ['Carousell',
   'Shopee Singapore Private Limited',
   '핀다 (Finda)',
   'WeWork Korea',
   '한빗코',
   'WeWork Japan',
   '라쿠텐(Rakuten)',
   '레드벨벳벤처스',
   '키드앱티브아시아']],
  JavaScript: [85,
  ['데이블(Dable)',
   '닥터다이어리',
   'KT NexR',
   '버즈아트(BBuzzArt)',
   '아틀라스가이드 (Atlas Guide)',
   '베스핀글로벌(Bespin)',
   '티드(envicase)',
   '스퀘어랩',
   '유라이크코리아',
   '지닉스(zeniex)',
   'Shopee',
   '인플루엔셜',
   'Peer',
   '올림플래닛(ZipView)',
   '루트에너지',
   '스타 팩토리 (Starfactory)',
   'XHIFT',
   '변호사 닷컴',
   '미로쿠 정보 서비스',
   '트루쇼트코리아(TrueShortKorea)',
   'The Encore Company',
   '펫닥',
   '크리마 (크리마팩토리, 크리마랩)',
   'Donuts',
   'R3',
   '트리플',
   '360Channel',
   '모두싸인',
   '스테이지랩스',
   '아이스크림에듀',
   'RakSul, Inc.']],
  AI: [84,
  ['매스프레소(Mathpresso)',
   '엠비아이솔루션',
   '브레인OS연구소',
   '루닛(Lunit)',
   '고퀄(GOQUAL)',
   'NAVER Corp(네이버)',
   '아틀라스가이드 (Atlas Guide)',
   '스퀘어랩',
   '엘리스',
   'FIN Concierge',
   '큐피스트',
   'Allganize Korea',
   'SoftBank (소프트뱅크)',
   '이쿠얼키',
   '패션을부탁해',
   'SUMMER',
   '스캐터랩(Scatterlab)',
   '코인매니저',
   '버즈니(Buzzni)',
   '옴니어스(Omnious)',
   '맵퍼스',
   'PERSOL TECHNOLOGY STAFF (퍼솔 테크놀로지 스태프)',
   '마인즈랩',
   '코인토스',
   '리얼리티리플렉션',
   '워트인텔리전스',
   'GS SHOP']],
  Global: [84,
  ['매스프레소(Mathpresso)',
   '데이블(Dable)',
   '머니브레인',
   'Talent Pool Project(Global)',
   '수아랩',
   '베스핀글로벌(Bespin)',
   '버즈빌(buzzvil)',
   '멜리펀트',
   '아모레퍼시픽(AMOREPACIFIC)',
   '어웨어(AWAIR)',
   '현대모비스',
   '뷰노']],
  Rails: [84,
  ['Level13',
   '스터디 플러스 (Studyplus)',
   '아만다(넥스트매치)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '클래스팅(Classting)',
   '패션을부탁해',
   '크리마 (크리마팩토리, 크리마랩)',
   '바닐라브릿지',
   '랭킹볼코리아',
   'Gunosy',
   '파레트코',
   '텀블벅(Tumblbug)',
   'RakSul, Inc.',
   '브래킷']],
  CI: [81,
  ['야놀자(yanolja)',
   '뉴스젤리(Newsjelly)',
   '터치웍스(touchworks)',
   '더파머스(마켓컬리)',
   '포잉(TRUST US)',
   '푸른밤',
   '사이버다임',
   '뷰티패스',
   '스터디 플러스 (Studyplus)',
   '오드컨셉',
   '트루쇼트코리아(TrueShortKorea)',
   '한국신용데이터',
   '클래스팅(Classting)',
   'Urbanfox Pte Ltd',
   '레이니스트(Banksalad)',
   '케어랩스 굿닥',
   '옴니어스(Omnious)',
   '라쿠텐(Rakuten)',
   '콜론디(Colondee)',
   '야놀자트래블(야놀자펜션)',
   '미스터픽',
   '모두싸인',
   '마이뮤직테이스트',
   'KLab Inc.',
   '해커스어학원']],
  Cloud: [81,
  ['스튜디오씨드코리아',
   '뉴스젤리(Newsjelly)',
   '닥터다이어리',
   '젠가엑스피티이엘티디',
   'Allganize Korea',
   '플레이윙즈',
   '콘텐츠연합플랫폼(pooq)',
   '레코벨(RECOBELL)',
   'SoftBank (소프트뱅크)',
   'Electronic Arts Korea I SPEARHEAD',
   '백패커(idus)',
   '한빗코',
   'RakSul, Inc.',
   '화해(버드뷰)',
   '브랜디(Brandi)']],
  RDBMS: [81,
  ['메디트(Medit)',
   '코인원(coinone)',
   '뉴스젤리(Newsjelly)',
   '피움랩스(PIUM LABS)',
   '스타 팩토리 (Starfactory)',
   '스페컴',
   '스타일쉐어',
   '어니스트펀드',
   '퀄슨',
   '엔젤스윙',
   '소리바다',
   '레이니스트(Banksalad)',
   'IDNSOFT',
   '레진엔터테인먼트',
   '콜론디(Colondee)',
   '그렙(grepp)',
   '왁티(WAGTI)',
   'Mobcast Games Inc.',
   '넥슨재팬 (NEXON)',
   '렌딧(LENDIT)',
   'Talent Pool Project(Japan)',
   '니프티',
   '뷰노',
   '노마드스타']],
  Angular: [80,
  ['솔라커넥트',
   '버키(balky)',
   '아틀라스가이드 (Atlas Guide)',
   '조이코퍼레이션(ZOYI)',
   '포지큐브',
   '유라이크코리아',
   '지닉스(zeniex)',
   '台灣樂天市場',
   '어반베이스(Urbanbase)',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '수퍼브(superb)',
   '카닥',
   '지니웍스(Genieworks, Inc.)',
   'Donuts',
   '플리토',
   '아이엠폼',
   '바닐라브릿지',
   '밸류앤드트러스트',
   '옐로스토리(Yellostory)',
   '파레트코',
   '모두싸인',
   '스테이지랩스',
   '아이스크림에듀',
   '이디엄',
   '뷰노',
   '노마드스타']],
  NoSQL: [80,
  ['비브로스',
   'ab180',
   '뉴스젤리(Newsjelly)',
   '피움랩스(PIUM LABS)',
   '버즈빌(buzzvil)',
   '아키드로우',
   'Blue Whale Foundation',
   '뷰티패스',
   '스페컴',
   '넷마블엔투',
   'Pulit',
   'Electronic Arts Korea I SPEARHEAD',
   '레이니스트(Banksalad)',
   '콜론디(Colondee)',
   '더커머스',
   'SK커뮤니케이션즈',
   '스테이지랩스',
   '렌딧(LENDIT)',
   '아이스크림에듀',
   '밀리만코리아(Milliman)',
   '뷰노',
   '키드앱티브아시아',
   '노마드스타']],
  Django: [77,
  ['코인원(coinone)',
   '뉴스젤리(Newsjelly)',
   '루닛(Lunit)',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '카카오페이지(podotree)',
   '엘리스',
   '다노(DANO)',
   '스펙업애드',
   '피알앤디컴퍼니(헤이딜러)',
   'Allganize Korea',
   '클래스팅(Classting)',
   '패션을부탁해',
   '버즈니(Buzzni)',
   '바닐라브릿지',
   'Gunosy',
   '파레트코',
   '제로웹',
   '디랩',
   '두나무(카카오스탁/업비트)',
   '뷰노',
   '브랜디(Brandi)']],
  OS: [74,
  ['(주)쿠차',
   '브레인OS연구소',
   '뉴스젤리(Newsjelly)',
   '버즈빌(buzzvil)',
   '아이엠랩(I.M.LAB)',
   '마크로밀 (Macromill)',
   'Shopee Singapore Private Limited',
   '위메프',
   '인포뱅크',
   '스트리미(Streami)',
   '웨이브일렉트로닉스',
   'WeWork Korea',
   'PERSOL TECHNOLOGY STAFF (퍼솔 테크놀로지 스태프)',
   'Chengbao',
   '360Channel',
   'SK커뮤니케이션즈',
   'COLOPL(코로프라)',
   '넥슨재팬 (NEXON)',
   '워트인텔리전스']],
  Amazon: [69,
  ['데이블(Dable)',
   '밸런스히어로 (트루밸런스)',
   'ab180',
   '고퀄(GOQUAL)',
   '피움랩스(PIUM LABS)',
   '더파머스(마켓컬리)',
   '스터디 플러스 (Studyplus)',
   '스타 팩토리 (Starfactory)',
   '카닥',
   '레코벨(RECOBELL)',
   '파레트코',
   '마이리얼플랜(아이지넷)',
   '텀블벅(Tumblbug)',
   '스테이지랩스']],
  Slack: [68,
  ['글로우데이즈(glowdayz)',
   '티드(envicase)',
   '스터디 플러스 (Studyplus)',
   '피알앤디컴퍼니(헤이딜러)',
   '스타 팩토리 (Starfactory)',
   '비피소프트',
   '변호사 닷컴',
   '오드컨셉',
   '카닥',
   '인포뱅크',
   '벤디스(식권대장)',
   '플리토',
   '레이니스트(Banksalad)',
   'Mobcast Games Inc.',
   '모두싸인',
   'RakSul, Inc.',
   '브래킷',
   '노마드스타']],
  Front: [67,
  ['메디트(Medit)',
   '야놀자(yanolja)',
   '스튜디오씨드코리아',
   '이스트엔드',
   '쿠프마케팅',
   'KT NexR',
   '글로우데이즈(glowdayz)',
   '스퀘어랩',
   '코인플러그(Coinplug)',
   '콜라비팀(Collabee)',
   '별별선생(티밸류와이즈)',
   '튜터링',
   '지닉스(zeniex)',
   '비알오',
   'Peer',
   '스펙업애드',
   '카닥',
   '데일리(DAILY)',
   '플레이윙즈',
   '크리마 (크리마팩토리, 크리마랩)',
   '컬쳐히어로',
   '아이오앤코 코리아',
   '뉴오더',
   '버즈니(Buzzni)',
   '한빗코',
   '에프앤에프(F&F)',
   '야놀자트래블(야놀자펜션)',
   '아이스크림에듀',
   '엔비티(NBT, 캐시슬라이드)',
   '(주)트릴리어네어']],
  SW: [67,
  ['고퀄(GOQUAL)',
   '피움랩스(PIUM LABS)',
   '수아랩',
   '아이엠랩(I.M.LAB)',
   '엘리스',
   '코드스테이츠 (CodeStates)',
   '드라마앤컴퍼니(리멤버)',
   '핀다 (Finda)',
   '오스템임플란트',
   '인포뱅크',
   '리디 주식회사(RIDIBOOKS)',
   '알서포트(Rsupport)',
   '밀리만코리아(Milliman)',
   '마인드원']],
  Hadoop: [66,
  ['ab180',
   '뉴스젤리(Newsjelly)',
   'KT NexR',
   '드라마앤컴퍼니(리멤버)',
   '소리바다',
   '리디 주식회사(RIDIBOOKS)',
   '아모레퍼시픽(AMOREPACIFIC)',
   'SK커뮤니케이션즈',
   '렌딧(LENDIT)',
   '재플(zapple)']],
  Kotlin: [66,
  ['Talent Pool Project(Global)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '아이엠랩(I.M.LAB)',
   '29CM(에이플러스비)',
   '스터디 플러스 (Studyplus)',
   '에스알유니버스',
   '크로키닷컴(ZIGZAG/지그재그)',
   '플레인베이글',
   '카닥',
   '빙글(Vingle)',
   '오피지지(OP.GG)',
   '뉴오더',
   '멜리펀트',
   'R3',
   '레이니스트(Banksalad)',
   '트리플',
   '요쿠스(Jocoos)',
   '제로웹',
   '피플펀드컴퍼니(PeopleFundCompany)']],
  Application: [63,
  ['알지피코리아(요기요,배달통)',
   'SK텔레콤(SKT)',
   '스튜디오씨드코리아',
   'KT NexR',
   '더파머스(마켓컬리)',
   '지닉스(zeniex)',
   '위메프',
   '카닥',
   '백패커(idus)',
   'Donuts',
   '알서포트(Rsupport)',
   '헬스커넥트',
   '브이픽스메디칼',
   '오비고(Obigo)',
   '이디엄',
   '시큐아이']],
  Google: [63,
  ['매스프레소(Mathpresso)',
   '데이블(Dable)',
   '밸런스히어로 (트루밸런스)',
   '뉴스젤리(Newsjelly)',
   '고퀄(GOQUAL)',
   '피움랩스(PIUM LABS)',
   '다노(DANO)',
   '피알앤디컴퍼니(헤이딜러)',
   '코드스테이츠 (CodeStates)',
   'Allganize Korea',
   '핀다 (Finda)',
   '휴레이포지티브',
   '다비오(Dabeeo)',
   'WeWork Korea',
   '멜리펀트',
   '센트비(Sentbe)',
   '한빗코',
   '레진엔터테인먼트',
   '모두싸인',
   'RakSul, Inc.',
   '뷰노',
   '브랜디(Brandi)']],
  Server: [63,
  ['비바리퍼블리카(Toss)',
   '야놀자(yanolja)',
   '코인원(coinone)',
   '台灣樂天市場',
   '엘리스',
   '힐링페이퍼',
   '크리마 (크리마팩토리, 크리마랩)',
   'Crypton (벡터스주식회사)',
   'WeWork Korea',
   '블록체인벤처스',
   '야놀자트래블(야놀자펜션)',
   '넥슨재팬 (NEXON)',
   '코인토스']],
  ONDA: [63, ['티포트(tport)']],
  App: [61,
  ['쿠프마케팅',
   '티드(envicase)',
   '데일리금융그룹',
   '台灣樂天市場',
   '에스알유니버스',
   '비티씨씨코리아',
   'dooub(둡)',
   '펫닥',
   '로켓런치',
   '멜리펀트',
   '아모레퍼시픽(AMOREPACIFIC)',
   '마이쿤',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '바로고(barogo)',
   'Talent Pool Project(Japan)']],
  Jenkins: [60,
  ['뉴스젤리(Newsjelly)',
   '루닛(Lunit)',
   '버즈빌(buzzvil)',
   '푸른밤',
   '스터디 플러스 (Studyplus)',
   '피알앤디컴퍼니(헤이딜러)',
   '변호사 닷컴',
   '트루쇼트코리아(TrueShortKorea)',
   '카닥',
   '인포뱅크',
   'Urbanfox Pte Ltd',
   '백패커(idus)',
   '자이냅스',
   '플리토',
   '360Channel',
   '레드벨벳벤처스',
   'Mobcast Games Inc.',
   '마이뮤직테이스트',
   'KLab Inc.']],
  Platform: [58,
  ['알지피코리아(요기요,배달통)',
   '메디트(Medit)',
   '고퀄(GOQUAL)',
   '애니펜',
   '지닉스(zeniex)',
   '트루쇼트코리아(TrueShortKorea)',
   'Allganize Korea',
   '지니웍스(Genieworks, Inc.)',
   'Crypton (벡터스주식회사)',
   'SUMMER',
   '아이오앤코 코리아',
   '테라핀테크(테라펀딩)',
   '라쿠텐(Rakuten)',
   '싸이월드',
   '마인즈랩',
   '코인토스']],
  GitHub: [58,
  ['솔라커넥트',
   'ab180',
   '닥터다이어리',
   '케어랩스(바비톡)',
   '티드(envicase)',
   '스터디 플러스 (Studyplus)',
   '아만다(넥스트매치)',
   '스타 팩토리 (Starfactory)',
   '와디즈',
   '로켓런치',
   '플리토',
   'CREARC',
   '레이니스트(Banksalad)',
   '케어랩스 굿닥',
   'RakSul, Inc.']],
  Spark: [57,
  ['ab180',
   '뉴스젤리(Newsjelly)',
   'NAVER Corp(네이버)',
   '글로우데이즈(glowdayz)',
   '드라마앤컴퍼니(리멤버)',
   'SUMMER',
   '아모레퍼시픽(AMOREPACIFIC)',
   '제로웹',
   '렌딧(LENDIT)',
   '엑스브레인(XBRAIN)']],
  Azure: [56,
  ['뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '루닛(Lunit)',
   '베스핀글로벌(Bespin)',
   '티드(envicase)',
   'XHIFT',
   'The Encore Company',
   'Talent Pool Project(Japan)',
   '브랜디(Brandi)']],
  DevOps: [55,
  ['마이리얼트립',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '푸른밤',
   'Level13',
   '큐피스트',
   '카닥',
   '레코벨(RECOBELL)',
   '루나소프트',
   'R3',
   '레이니스트(Banksalad)',
   '케어랩스 굿닥',
   '옴니어스(Omnious)',
   '라쿠텐(Rakuten)',
   '콜론디(Colondee)',
   '원스토어',
   '발란(BALAAN)',
   '텀블벅(Tumblbug)',
   '마이뮤직테이스트',
   '뷰노',
   '씨엔알리서치',
   '노마드스타']],
  Windows: [54,
  ['마크로밀 (Macromill)',
   'Shopee Singapore Private Limited',
   '데일리(DAILY)',
   '힐세리온',
   'WeWork Korea',
   'Chengbao',
   '360Channel',
   '코인토스']],
  Github: [53,
  ['비바리퍼블리카(Toss)',
   '터치웍스(touchworks)',
   '아틀라스가이드 (Atlas Guide)',
   '비버이엔티',
   '튜터링',
   '엘리스',
   '스펙업애드',
   '피알앤디컴퍼니(헤이딜러)',
   '루트에너지',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '드라마앤컴퍼니(리멤버)',
   '벤디스(식권대장)',
   '크리마 (크리마팩토리, 크리마랩)',
   '우아한형제들(배달의민족,Tech)',
   '로켓런치',
   'Donuts',
   '어웨어(AWAIR)',
   '그렙(grepp)',
   '메탑스 (metaps)',
   'Mobcast Games Inc.',
   '모두싸인',
   '휴톰',
   '브래킷',
   '(주)트릴리어네어']],
  framework: [53,
  ['뉴스젤리(Newsjelly)',
   '루닛(Lunit)',
   '닥터다이어리',
   '글로우데이즈(glowdayz)',
   '칩스앤미디어',
   '지닉스(zeniex)',
   'Shopee',
   '푸른밤',
   '클래스팅(Classting)',
   '어니스트펀드',
   '패션을부탁해',
   '라쿠텐(Rakuten)',
   '레드벨벳벤처스',
   '알서포트(Rsupport)',
   '헬스커넥트']],
  RDS: [53,
  ['메디트(Medit)',
   '버즈아트(BBuzzArt)',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '쏘카(SOCAR)',
   '비알오',
   '스터디 플러스 (Studyplus)',
   '큐피스트',
   '한국신용데이터',
   'Pulit',
   'Urbanfox Pte Ltd',
   '바닐라브릿지',
   '제로웹',
   '왁티(WAGTI)',
   '텀블벅(Tumblbug)',
   'RakSul, Inc.',
   '브랜디(Brandi)']],
  web: [52,
  ['올스타메니지먼트',
   '스퀘어랩',
   'Shopee Singapore Private Limited',
   '台灣樂天市場',
   '엘리스',
   'Allganize Korea',
   '핀다 (Finda)',
   'Crypton (벡터스주식회사)',
   '블록체인벤처스',
   '한빗코',
   '미스터픽',
   '원스토어',
   '메탑스 (metaps)',
   '엔비티(NBT, 캐시슬라이드)']],
  Back: [52,
  ['메디트(Medit)',
   'KT NexR',
   '링크샵스(linkshops)',
   '스퀘어랩',
   '별별선생(티밸류와이즈)',
   '튜터링',
   '푸른밤',
   '펫닥',
   '벤디스(식권대장)',
   '크리마 (크리마팩토리, 크리마랩)',
   '아이오앤코 코리아',
   '디케이테크인(dk techin) a kakao company',
   '델레오(Deleo)',
   '아이스크림에듀']],
  Native: [51,
  ['콜라비팀(Collabee)',
   '푸른밤',
   '인플루엔셜',
   '플레인베이글',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '(주)브레이브모바일(soomgo)',
   '카닥',
   'Allganize Korea',
   '펫닥',
   '멜리펀트',
   '넥스트리밍',
   '코인매니저',
   'CREARC',
   '바로고(barogo)',
   '모두싸인',
   '(주)트릴리어네어']],
  Go: [51,
  ['ab180',
   '뉴스젤리(Newsjelly)',
   'PUBG Corporation',
   '버즈빌(buzzvil)',
   '더루프',
   '카닥',
   '360Channel',
   'COLOPL(코로프라)',
   '메디블록(MediBloc)',
   '두나무(카카오스탁/업비트)']],
  Mobile: [50,
  ['모비데이즈(Mobidays)',
   '뷰티패스',
   '에스알유니버스',
   'FIN Concierge',
   '뉴지스탁(DFG)',
   '지니웍스(Genieworks, Inc.)',
   '힐세리온',
   '아이오앤코 코리아',
   '멜리펀트',
   '아이엠폼',
   '한국선불카드',
   '헬스커넥트',
   '리얼리티리플렉션',
   '헤카스(HECAS)',
   '키드앱티브아시아']],
  Objective: [49,
  ['Talent Pool Project(Global)',
   '딜라이트룸(Alarmy)',
   '토스랩(JANDI)',
   '비피소프트',
   '오드컨셉',
   '카닥',
   '뤼이드(Riiid)',
   '우아한형제들(배달의민족,Tech)',
   '로켓런치',
   '차차크리에이션',
   'CREARC',
   '케어랩스 굿닥',
   '마이쿤',
   '싸이월드',
   '바로고(barogo)',
   '360Channel',
   'VCNC(비트윈)',
   '알서포트(Rsupport)',
   'Talent Pool Project']],
  HTTP: [49,
  ['보이스로코',
   '29CM(에이플러스비)',
   '엘리스',
   '어반베이스(Urbanbase)',
   '카닥',
   '데일리(DAILY)',
   '뉴오더',
   '레이니스트(Banksalad)',
   '야놀자트래블(야놀자펜션)',
   '미스터픽']],
  TDD: [48,
  ['뉴스젤리(Newsjelly)',
   '티드(envicase)',
   '아이엠랩(I.M.LAB)',
   '조이코퍼레이션(ZOYI)',
   '푸른밤',
   '사이버다임',
   '뷰티패스',
   '아주큐엠에스',
   '아만다(넥스트매치)',
   '큐피스트',
   '더루프',
   '클래스팅(Classting)',
   '빙글(Vingle)',
   '마이리얼플랜(아이지넷)',
   '레드벨벳벤처스',
   '모두싸인']],
  Engineer: [48,
  ['SK텔레콤(SKT)',
   '고퀄(GOQUAL)',
   'Electronic Arts Korea I SPEARHEAD',
   '크리마 (크리마팩토리, 크리마랩)',
   '컬쳐히어로',
   '리디 주식회사(RIDIBOOKS)',
   '레저큐',
   '렌딧(LENDIT)',
   '키드앱티브아시아',
   '엑스브레인(XBRAIN)']],
  Scala: [48,
  ['NAVER Corp(네이버)', '카닥', 'R3', '리디 주식회사(RIDIBOOKS)', '레이니스트(Banksalad)']],
  Webpack: [47,
  ['원티드랩',
   '비바리퍼블리카(Toss)',
   '버키(balky)',
   '뉴스젤리(Newsjelly)',
   '올스타메니지먼트',
   '조이코퍼레이션(ZOYI)',
   '지닉스(zeniex)',
   '오케이코인코리아',
   'Peer',
   '올림플래닛(ZipView)',
   '어반베이스(Urbanbase)',
   '데일리(DAILY)',
   '컬쳐히어로',
   'Donuts',
   '한빗코',
   '메탑스 (metaps)',
   '모두싸인',
   '이디엄']],
  MongoDB: [47,
  ['머니브레인',
   '아그레아블',
   '닥터다이어리',
   '유저해빗(UserHabit)',
   '아키드로우',
   '뷰티패스',
   '엘리스',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '콘텐츠연합플랫폼(pooq)',
   'The Encore Company',
   '넷마블엔투',
   'Pulit',
   'Electronic Arts Korea I SPEARHEAD',
   '퀄슨',
   '플리토',
   '라쿠텐(Rakuten)',
   '아이스크림에듀',
   '브래킷']],
  MVP: [47,
  ['버킷플레이스(오늘의집)',
   '체인파트너스',
   '마크로밀 (Macromill)',
   '더루프',
   '카닥',
   '우아한형제들(배달의민족,Tech)',
   'Donuts',
   '멜리펀트',
   '넥스트리밍',
   'Gunosy',
   'RakSul, Inc.']],
  Redux: [46,
  ['스튜디오씨드코리아',
   '아틀라스가이드 (Atlas Guide)',
   '조이코퍼레이션(ZOYI)',
   '포지큐브',
   '지닉스(zeniex)',
   '푸른밤',
   '오케이코인코리아',
   '파이브락스(5Rocks)',
   '탭조이코리아(Tapjoy)',
   '힐링페이퍼',
   '펫닥',
   '뤼이드(Riiid)',
   '컬쳐히어로',
   '한빗코',
   '모두싸인']],
  AngularJS: [46,
  ['원티드랩',
   '데이블(Dable)',
   '머니브레인',
   '메디트(Medit)',
   '뉴스젤리(Newsjelly)',
   '더블유컨셉코리아(wconcept)',
   '버즈빌(buzzvil)',
   '소다크루',
   '지닉스(zeniex)',
   'Peer',
   '플레이윙즈',
   '이쿠얼키',
   '라쿠텐(Rakuten)',
   '브래킷',
   '미탭스플러스']],
  Kubernetes: [46,
  ['버즈빌(buzzvil)',
   'Allganize Korea',
   '플리토',
   '레이니스트(Banksalad)',
   'COLOPL(코로프라)',
   '마이뮤직테이스트']],
  PM: [45,
  ['야놀자(yanolja)',
   '코인원(coinone)',
   '뉴스젤리(Newsjelly)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '푸른밤',
   '인플루엔셜',
   '에스알유니버스',
   '다노(DANO)',
   '아크로고스 주식회사',
   'Jr코딩연구소',
   '더블미코리아',
   '엔젤스윙',
   '루나소프트',
   '바닐라브릿지',
   '한빗코',
   '번개장터(셀잇)',
   '헬스커넥트',
   '브이픽스메디칼',
   '헤카스(HECAS)']],
  Jira: [45,
  ['뉴스젤리(Newsjelly)',
   '딜라이트룸(Alarmy)',
   '버즈빌(buzzvil)',
   '포지큐브',
   'XHIFT',
   '핀다 (Finda)',
   '휴레이포지티브',
   '벤디스(식권대장)',
   '우아한형제들(배달의민족,Tech)',
   '플리토',
   '더커머스',
   '제로웹',
   '피플펀드컴퍼니(PeopleFundCompany)',
   '레드벨벳벤처스',
   'Mobcast Games Inc.',
   '노마드스타']],
  DynamoDB: [45,
  ['글로우데이즈(glowdayz)', '버즈빌(buzzvil)', '뷰티패스', '패션을부탁해', '벤디스(식권대장)', '제로웹']],
  IoT: [44,
  ['와이브레인(YBrain)',
   '고퀄(GOQUAL)',
   '피움랩스(PIUM LABS)',
   '아이엠랩(I.M.LAB)',
   'SoftBank (소프트뱅크)',
   'SUMMER',
   '웰트(WELT)',
   '메텔(Maetel)',
   '제로웹',
   'PERSOL TECHNOLOGY STAFF (퍼솔 테크놀로지 스태프)']],
  Architecture: [44,
  ['알지피코리아(요기요,배달통)',
   '피터팬의 좋은방 구하기(PETERPANZ)',
   '큐피스트',
   '위메프',
   '트루쇼트코리아(TrueShortKorea)',
   '레코벨(RECOBELL)',
   'Electronic Arts Korea I SPEARHEAD',
   '레이니스트(Banksalad)',
   '마이리얼플랜(아이지넷)',
   '스프링웍스(Springworks)',
   '브랜디(Brandi)']],
  JAVA: [43,
  ['푸른밤',
   '아주큐엠에스',
   '비즈톡',
   '퀄슨',
   '백패커(idus)',
   '다비오(Dabeeo)',
   'IDNSOFT',
   '에프앤에프(F&F)',
   '레진엔터테인먼트',
   '델레오(Deleo)',
   '아르고넷']],
  Unity: [43,
  ['SendBird(센드버드)',
   '애니펜',
   '스마트스터디(SMARTSTUDY)',
   '스노우(SNOW)',
   'Obelab',
   '360Channel',
   '휴톰',
   '리얼리티리플렉션',
   '데브시스터즈(Devsisters)',
   'KLab Inc.',
   '헤카스(HECAS)']],
  Elasticsearch: [43,
  ['피터팬의 좋은방 구하기(PETERPANZ)',
   '글로우데이즈(glowdayz)',
   '버즈빌(buzzvil)',
   '스퀘어랩',
   '큐피스트',
   '백패커(idus)']],
  Studyplus: [43, ['스터디 플러스 (Studyplus)']],
  SPA: [41,
  ['버키(balky)',
   '더블유컨셉코리아(wconcept)',
   '올스타메니지먼트',
   '아틀라스가이드 (Atlas Guide)',
   '조이코퍼레이션(ZOYI)',
   '오케이코인코리아',
   '이쿠얼키',
   '컬쳐히어로',
   'Donuts',
   '이디엄',
   'RakSul, Inc.']],
  Business: [41,
  ['비바리퍼블리카(Toss)',
   '카카오모빌리티(KakaoMobility)',
   'Carousell',
   '라이나생명보험',
   '비피소프트',
   '뉴지스탁(DFG)',
   'WeWork Korea',
   '테라핀테크(테라펀딩)',
   '라쿠텐(Rakuten)',
   '스테이지랩스']],
  Test: [40,
  ['아이엠랩(I.M.LAB)',
   '키즈노트',
   '아주큐엠에스',
   '(주)브레이브모바일(soomgo)',
   '빙글(Vingle)',
   '아모레퍼시픽(AMOREPACIFIC)',
   '마이리얼플랜(아이지넷)',
   '레드벨벳벤처스',
   '모두싸인']],
  Solution: [40,
  ['더파머스(마켓컬리)',
   'FIN Concierge',
   '오스템임플란트',
   '아이엠폼',
   '한국선불카드',
   '알서포트(Rsupport)',
   '헬스커넥트',
   '브이픽스메디칼']],
  PostgreSQL: [39,
  ['코인원(coinone)',
   '뉴스젤리(Newsjelly)',
   '엘리스',
   '한국신용데이터',
   '스타일쉐어',
   'Urbanfox Pte Ltd',
   '플리토',
   '그렙(grepp)',
   '니프티',
   '투게더앱스',
   '키드앱티브아시아']],
  Apache: [39,
  ['메디트(Medit)',
   '모비데이즈(Mobidays)',
   '뉴스젤리(Newsjelly)',
   '글로우데이즈(glowdayz)',
   '더파머스(마켓컬리)',
   '台灣樂天市場',
   '루트에너지',
   '블로코(blocko)',
   '디케이테크인(dk techin) a kakao company',
   '라쿠텐(Rakuten)',
   '미스터픽']],
  Oracle: [39,
  ['메디트(Medit)',
   '카카오모빌리티(KakaoMobility)',
   '코인원(coinone)',
   '더파머스(마켓컬리)',
   '마크로밀 (Macromill)',
   '다비오(Dabeeo)',
   '헬스커넥트',
   '니프티',
   '워트인텔리전스',
   '원더피플',
   '마인드원']],
  Design: [38,
  ['스튜디오씨드코리아',
   'Carousell',
   'Shopee',
   '台灣樂天市場',
   '크로키닷컴(ZIGZAG/지그재그)',
   '큐피스트',
   'WeWork Japan',
   'Chengbao',
   '마이리얼플랜(아이지넷)',
   '알서포트(Rsupport)',
   '키드앱티브아시아']],
  GCP: [38,
  ['아만다(넥스트매치)',
   'The Encore Company',
   '백패커(idus)',
   '비주얼(bejewel)',
   '콜론디(Colondee)',
   'Mobcast Games Inc.']],
  Agile: [37,
  ['버킷플레이스(오늘의집)',
   '지닉스(zeniex)',
   '엘리스',
   '코드스테이츠 (CodeStates)',
   '(주)브레이브모바일(soomgo)',
   '오드컨셉',
   'Allganize Korea',
   '레코벨(RECOBELL)',
   '레저큐',
   '라쿠텐(Rakuten)',
   '콜론디(Colondee)',
   '레드벨벳벤처스',
   '휴톰',
   '개념원리']],
  Backend: [37,
  ['푸른밤',
   '엘리스',
   '트루쇼트코리아(TrueShortKorea)',
   'Crypton (벡터스주식회사)',
   '다비오(Dabeeo)',
   '아이오앤코 코리아',
   '아이엠폼',
   '레저큐',
   '레드벨벳벤처스',
   '아이스크림에듀']]
};

module.exports = {
  companyTags
};
